- name: Deploying Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: Fail when not AWS
    fail:
    when: input.environment.aws is not defined

  - name: Create an EC2 Instance
    ec2_instance:
      name: equail-lnx1
      state: running
      region: "{{ input.environment.aws.region }}"
      instance_type:  "{{ input.environment.aws.vm_size }}"
      security_group: sg-a9add2d0
      image_id: ami-0520e698dd500b1d1
      key_name: equail_lab
      network:
        assign_public_ip: true
    register: output

  - name: Saving Provisioned IP Address
    set_stats:
      data:
        provision_ip: "{{ output.instances[0].public_ip_address }}"
