- name: Deploying Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: Including input variables
    include_vars:
      file: input.json
      name: input

  - name: Debugging
    debug:
      msg: "{{ input }}"

  - name: Setting input as stats
    set_stats:
      input: "{{ input }}"